import { TemplateType } from "../types";

// 🚀 PLANTILLA 1: Event-Driven Architecture
const eventDrivenTemplate: TemplateType = {
  id: "event-driven-architecture",
  name: "🚀 Event-Driven Architecture",
  description:
    "Arquitectura moderna basada en eventos para aplicaciones escalables y resilientes con patrones asíncronos.",
  image: "/templates/event-driven.png",
  version: "2.0",
  nodes: [
    {
      id: "user-interface",
      type: "square size:280x120",
      position: { x: 50, y: 50 },
      size: { width: 280, height: 120 },
      text: "User Interface\n(React/Angular)",
      iconType: "web",
      backgroundColor: "#E3F2FD",
    },
    {
      id: "api-gateway",
      type: "square size:300x100",
      position: { x: 450, y: 75 },
      size: { width: 300, height: 100 },
      text: "API Gateway",
      iconType: "aws-api-gateway",
      backgroundColor: "#FFF3E0",
    },
    {
      id: "command-handler",
      type: "square size:240x90",
      position: { x: 100, y: 250 },
      size: { width: 240, height: 90 },
      text: "Command Handler",
      iconType: "aws-lambda",
      backgroundColor: "#F3E5F5",
    },
    {
      id: "event-bus",
      type: "square size:350x120",
      position: { x: 400, y: 230 },
      size: { width: 350, height: 120 },
      text: "Event Bus\n(EventBridge/Kafka)",
      iconType: "aws-eventbridge",
      backgroundColor: "#E8F5E8",
    },
    {
      id: "event-store",
      type: "square size:200x80",
      position: { x: 820, y: 250 },
      size: { width: 200, height: 80 },
      text: "Event Store",
      iconType: "database",
      backgroundColor: "#FCE4EC",
    },
    {
      id: "notification-service",
      type: "square size:220x90",
      position: { x: 120, y: 420 },
      size: { width: 220, height: 90 },
      text: "Notification Service",
      iconType: "aws-sns",
      backgroundColor: "#FFF8E1",
    },
    {
      id: "analytics-service",
      type: "square size:220x90",
      position: { x: 420, y: 420 },
      size: { width: 220, height: 90 },
      text: "Analytics Service",
      iconType: "analytics",
      backgroundColor: "#E1F5FE",
    },
    {
      id: "audit-service",
      type: "square size:220x90",
      position: { x: 720, y: 420 },
      size: { width: 220, height: 90 },
      text: "Audit Service",
      iconType: "security",
      backgroundColor: "#EFEBE9",
    },
  ],
  connections: [
    {
      id: "ui-to-gateway",
      sourceId: "user-interface",
      targetId: "api-gateway",
      sourcePosition: "right",
      targetPosition: "left",
      sourceX: 330,
      sourceY: 110,
      targetX: 450,
      targetY: 125,
      style: "solid",
      animation: "traveling-dot-fast",
      color: "#1976D2",
      strokeWidth: 3,
      endArrowHead: "arrow",
    },
    {
      id: "gateway-to-command",
      sourceId: "api-gateway",
      targetId: "command-handler",
      sourcePosition: "bottom",
      targetPosition: "top",
      sourceX: 600,
      sourceY: 175,
      targetX: 220,
      targetY: 250,
      style: "solid",
      animation: "traveling-dot",
      color: "#388E3C",
      strokeWidth: 3,
      endArrowHead: "arrow",
    },
    {
      id: "command-to-eventbus",
      sourceId: "command-handler",
      targetId: "event-bus",
      sourcePosition: "right",
      targetPosition: "left",
      sourceX: 340,
      sourceY: 295,
      targetX: 400,
      targetY: 290,
      style: "solid",
      animation: "pulse",
      color: "#7B1FA2",
      strokeWidth: 4,
      endArrowHead: "arrow",
    },
    {
      id: "eventbus-to-store",
      sourceId: "event-bus",
      targetId: "event-store",
      sourcePosition: "right",
      targetPosition: "left",
      sourceX: 750,
      sourceY: 290,
      targetX: 820,
      targetY: 290,
      style: "solid",
      animation: "traveling-dot-fastest",
      color: "#D32F2F",
      strokeWidth: 3,
      endArrowHead: "arrow",
    },
    {
      id: "eventbus-to-notification",
      sourceId: "event-bus",
      targetId: "notification-service",
      sourcePosition: "bottom",
      targetPosition: "top",
      sourceX: 475,
      sourceY: 350,
      targetX: 230,
      targetY: 420,
      style: "dashed",
      animation: "dash",
      color: "#F57C00",
      strokeWidth: 2,
      endArrowHead: "arrow",
    },
    {
      id: "eventbus-to-analytics",
      sourceId: "event-bus",
      targetId: "analytics-service",
      sourcePosition: "bottom",
      targetPosition: "top",
      sourceX: 575,
      sourceY: 350,
      targetX: 530,
      targetY: 420,
      style: "dashed",
      animation: "dash",
      color: "#0288D1",
      strokeWidth: 2,
      endArrowHead: "arrow",
    },
    {
      id: "eventbus-to-audit",
      sourceId: "event-bus",
      targetId: "audit-service",
      sourcePosition: "bottom",
      targetPosition: "top",
      sourceX: 675,
      sourceY: 350,
      targetX: 830,
      targetY: 420,
      style: "dashed",
      animation: "dash",
      color: "#5D4037",
      strokeWidth: 2,
      endArrowHead: "arrow",
    },
  ],
  viewport: {
    scale: 0.8,
    position: { x: 50, y: 50 },
  },
  metadata: {
    exportedAt: new Date().toISOString(),
    nodeCount: 8,
    connectionCount: 7,
  },
};

// 🏗️ PLANTILLA 2: CQRS & Event Sourcing
const cqrsEventSourcingTemplate: TemplateType = {
  id: "cqrs-event-sourcing",
  name: "🏗️ CQRS & Event Sourcing",
  description:
    "Patrón avanzado de separación de comandos y consultas con almacenamiento de eventos para máxima escalabilidad.",
  image: "/templates/cqrs-event-sourcing.png",
  version: "2.0",
  nodes: [
    {
      id: "client-apps",
      type: "square size:280x100",
      position: { x: 50, y: 80 },
      size: { width: 280, height: 100 },
      text: "Client Applications",
      iconType: "mobile",
      backgroundColor: "#E8EAF6",
    },
    {
      id: "command-api",
      type: "square size:200x120",
      position: { x: 100, y: 250 },
      size: { width: 200, height: 120 },
      text: "Command API\n(Write Side)",
      iconType: "api",
      backgroundColor: "#FFEBEE",
    },
    {
      id: "query-api",
      type: "square size:200x120",
      position: { x: 500, y: 250 },
      size: { width: 200, height: 120 },
      text: "Query API\n(Read Side)",
      iconType: "api",
      backgroundColor: "#E0F2F1",
    },
    {
      id: "command-handlers",
      type: "square size:220x90",
      position: { x: 90, y: 420 },
      size: { width: 220, height: 90 },
      text: "Command Handlers",
      iconType: "aws-lambda",
      backgroundColor: "#FFF3E0",
    },
    {
      id: "domain-model",
      type: "square size:200x80",
      position: { x: 100, y: 570 },
      size: { width: 200, height: 80 },
      text: "Domain Model",
      iconType: "config",
      backgroundColor: "#F3E5F5",
    },
    {
      id: "event-store-cqrs",
      type: "square size:250x100",
      position: { x: 375, y: 520 },
      size: { width: 250, height: 100 },
      text: "Event Store\n(Source of Truth)",
      iconType: "database",
      backgroundColor: "#FCE4EC",
    },
    {
      id: "read-models",
      type: "square size:220x90",
      position: { x: 490, y: 420 },
      size: { width: 220, height: 90 },
      text: "Read Models",
      iconType: "database",
      backgroundColor: "#E8F5E8",
    },
    {
      id: "projections",
      type: "square size:200x80",
      position: { x: 700, y: 350 },
      size: { width: 200, height: 80 },
      text: "Projections",
      iconType: "analytics",
      backgroundColor: "#E1F5FE",
    },
    {
      id: "event-handlers",
      type: "square size:200x80",
      position: { x: 700, y: 520 },
      size: { width: 200, height: 80 },
      text: "Event Handlers",
      iconType: "aws-lambda",
      backgroundColor: "#FFF8E1",
    },
  ],
  connections: [
    {
      id: "client-to-command",
      sourceId: "client-apps",
      targetId: "command-api",
      sourcePosition: "bottom",
      targetPosition: "top",
      sourceX: 150,
      sourceY: 180,
      targetX: 200,
      targetY: 250,
      style: "solid",
      animation: "traveling-dot",
      color: "#D32F2F",
      strokeWidth: 3,
      endArrowHead: "arrow",
    },
    {
      id: "client-to-query",
      sourceId: "client-apps",
      targetId: "query-api",
      sourcePosition: "bottom",
      targetPosition: "top",
      sourceX: 250,
      sourceY: 180,
      targetX: 600,
      targetY: 250,
      style: "solid",
      animation: "traveling-dot",
      color: "#388E3C",
      strokeWidth: 3,
      endArrowHead: "arrow",
    },
    {
      id: "command-api-to-handlers",
      sourceId: "command-api",
      targetId: "command-handlers",
      sourcePosition: "bottom",
      targetPosition: "top",
      sourceX: 200,
      sourceY: 370,
      targetX: 200,
      targetY: 420,
      style: "solid",
      animation: "pulse",
      color: "#7B1FA2",
      strokeWidth: 4,
      endArrowHead: "arrow",
    },
    {
      id: "handlers-to-domain",
      sourceId: "command-handlers",
      targetId: "domain-model",
      sourcePosition: "bottom",
      targetPosition: "top",
      sourceX: 200,
      sourceY: 510,
      targetX: 200,
      targetY: 570,
      style: "solid",
      animation: "traveling-dot-fast",
      color: "#F57C00",
      strokeWidth: 3,
      endArrowHead: "arrow",
    },
    {
      id: "domain-to-eventstore",
      sourceId: "domain-model",
      targetId: "event-store-cqrs",
      sourcePosition: "right",
      targetPosition: "left",
      sourceX: 300,
      sourceY: 610,
      targetX: 375,
      targetY: 570,
      style: "solid",
      animation: "traveling-dot-fastest",
      color: "#1976D2",
      strokeWidth: 4,
      endArrowHead: "arrow",
    },
    {
      id: "eventstore-to-handlers",
      sourceId: "event-store-cqrs",
      targetId: "event-handlers",
      sourcePosition: "right",
      targetPosition: "left",
      sourceX: 625,
      sourceY: 570,
      targetX: 700,
      targetY: 560,
      style: "dashed",
      animation: "dash",
      color: "#FF6F00",
      strokeWidth: 2,
      endArrowHead: "arrow",
    },
    {
      id: "handlers-to-projections",
      sourceId: "event-handlers",
      targetId: "projections",
      sourcePosition: "top",
      targetPosition: "bottom",
      sourceX: 800,
      sourceY: 520,
      targetX: 800,
      targetY: 430,
      style: "solid",
      animation: "flow",
      color: "#0288D1",
      strokeWidth: 3,
      endArrowHead: "arrow",
    },
    {
      id: "projections-to-readmodels",
      sourceId: "projections",
      targetId: "read-models",
      sourcePosition: "left",
      targetPosition: "right",
      sourceX: 700,
      sourceY: 390,
      targetX: 710,
      targetY: 465,
      style: "solid",
      animation: "traveling-dot",
      color: "#689F38",
      strokeWidth: 3,
      endArrowHead: "arrow",
    },
    {
      id: "readmodels-to-query",
      sourceId: "read-models",
      targetId: "query-api",
      sourcePosition: "top",
      targetPosition: "bottom",
      sourceX: 600,
      sourceY: 420,
      targetX: 600,
      targetY: 370,
      style: "solid",
      animation: "pulse",
      color: "#5D4037",
      strokeWidth: 3,
      endArrowHead: "arrow",
    },
  ],
  viewport: {
    scale: 0.7,
    position: { x: 80, y: 60 },
  },
  metadata: {
    exportedAt: new Date().toISOString(),
    nodeCount: 9,
    connectionCount: 10,
  },
};

// ☁️ PLANTILLA 3: Multi-Cloud Architecture
const multiCloudTemplate: TemplateType = {
  id: "multi-cloud-architecture",
  name: "☁️ Multi-Cloud Architecture",
  description:
    "Arquitectura empresarial distribuida usando AWS, GCP y Azure para máxima disponibilidad y flexibilidad.",
  image: "/templates/multi-cloud.png",
  version: "2.0",
  nodes: [
    {
      id: "global-lb",
      type: "square size:300x80",
      position: { x: 400, y: 50 },
      size: { width: 300, height: 80 },
      text: "Global Load Balancer",
      iconType: "aws-cloudfront",
      backgroundColor: "#E3F2FD",
    },
    {
      id: "aws-region",
      type: "square size:350x200",
      position: { x: 100, y: 200 },
      size: { width: 350, height: 200 },
      text: "AWS Region (us-east-1)\n\n• EKS Cluster\n• RDS PostgreSQL\n• ElastiCache Redis\n• S3 Storage",
      iconType: "aws-ec2",
      backgroundColor: "#FFF3E0",
    },
    {
      id: "gcp-region",
      type: "square size:350x200",
      position: { x: 500, y: 200 },
      size: { width: 350, height: 200 },
      text: "GCP Region (us-central1)\n\n• GKE Cluster\n• Cloud SQL\n• Memorystore\n• Cloud Storage",
      iconType: "cloud",
      backgroundColor: "#E8F5E8",
    },
    {
      id: "azure-region",
      type: "square size:350x200",
      position: { x: 900, y: 200 },
      size: { width: 350, height: 200 },
      text: "Azure Region (East US)\n\n• AKS Cluster\n• Azure SQL\n• Redis Cache\n• Blob Storage",
      iconType: "cloud",
      backgroundColor: "#E1F5FE",
    },
    {
      id: "monitoring",
      type: "square size:250x100",
      position: { x: 200, y: 480 },
      size: { width: 250, height: 100 },
      text: "Multi-Cloud Monitoring\n(Datadog/New Relic)",
      iconType: "analytics",
      backgroundColor: "#F3E5F5",
    },
    {
      id: "backup-sync",
      type: "square size:250x100",
      position: { x: 500, y: 480 },
      size: { width: 250, height: 100 },
      text: "Cross-Cloud Backup\n& Data Sync",
      iconType: "database",
      backgroundColor: "#FCE4EC",
    },
    {
      id: "security-center",
      type: "square size:250x100",
      position: { x: 800, y: 480 },
      size: { width: 250, height: 100 },
      text: "Unified Security\nCenter",
      iconType: "security",
      backgroundColor: "#EFEBE9",
    },
  ],
  connections: [
    {
      id: "lb-to-aws",
      sourceId: "global-lb",
      targetId: "aws-region",
      sourcePosition: "bottom",
      targetPosition: "top",
      sourceX: 500,
      sourceY: 130,
      targetX: 275,
      targetY: 200,
      style: "solid",
      animation: "traveling-dot-fast",
      color: "#FF9800",
      strokeWidth: 4,
      endArrowHead: "arrow",
    },
    {
      id: "lb-to-gcp",
      sourceId: "global-lb",
      targetId: "gcp-region",
      sourcePosition: "bottom",
      targetPosition: "top",
      sourceX: 550,
      sourceY: 130,
      targetX: 675,
      targetY: 200,
      style: "solid",
      animation: "traveling-dot-fast",
      color: "#4CAF50",
      strokeWidth: 4,
      endArrowHead: "arrow",
    },
    {
      id: "lb-to-azure",
      sourceId: "global-lb",
      targetId: "azure-region",
      sourcePosition: "bottom",
      targetPosition: "top",
      sourceX: 600,
      sourceY: 130,
      targetX: 1075,
      targetY: 200,
      style: "solid",
      animation: "traveling-dot-fast",
      color: "#2196F3",
      strokeWidth: 4,
      endArrowHead: "arrow",
    },
    {
      id: "aws-to-gcp-sync",
      sourceId: "aws-region",
      targetId: "gcp-region",
      sourcePosition: "right",
      targetPosition: "left",
      sourceX: 450,
      sourceY: 300,
      targetX: 500,
      targetY: 300,
      style: "dashed",
      animation: "dash",
      color: "#9C27B0",
      strokeWidth: 3,
      endArrowHead: "arrow",
    },
    {
      id: "gcp-to-azure-sync",
      sourceId: "gcp-region",
      targetId: "azure-region",
      sourcePosition: "right",
      targetPosition: "left",
      sourceX: 850,
      sourceY: 300,
      targetX: 900,
      targetY: 300,
      style: "dashed",
      animation: "dash",
      color: "#9C27B0",
      strokeWidth: 3,
      endArrowHead: "arrow",
    },
    {
      id: "aws-to-monitoring",
      sourceId: "aws-region",
      targetId: "monitoring",
      sourcePosition: "bottom",
      targetPosition: "top",
      sourceX: 275,
      sourceY: 400,
      targetX: 325,
      targetY: 480,
      style: "dotted",
      animation: "flow",
      color: "#607D8B",
      strokeWidth: 2,
      endArrowHead: "arrow",
    },
    {
      id: "gcp-to-backup",
      sourceId: "gcp-region",
      targetId: "backup-sync",
      sourcePosition: "bottom",
      targetPosition: "top",
      sourceX: 675,
      sourceY: 400,
      targetX: 625,
      targetY: 480,
      style: "dotted",
      animation: "flow",
      color: "#607D8B",
      strokeWidth: 2,
      endArrowHead: "arrow",
    },
    {
      id: "azure-to-security",
      sourceId: "azure-region",
      targetId: "security-center",
      sourcePosition: "bottom",
      targetPosition: "top",
      sourceX: 1075,
      sourceY: 400,
      targetX: 925,
      targetY: 480,
      style: "dotted",
      animation: "flow",
      color: "#607D8B",
      strokeWidth: 2,
      endArrowHead: "arrow",
    },
  ],
  viewport: {
    scale: 0.6,
    position: { x: 100, y: 80 },
  },
  metadata: {
    exportedAt: new Date().toISOString(),
    nodeCount: 7,
    connectionCount: 8,
  },
};

// 🛒 PLANTILLA 4: E-commerce Microservices
const ecommerceMicroservicesTemplate: TemplateType = {
  id: "ecommerce-microservices",
  name: "🛒 E-commerce Microservices",
  description:
    "Plataforma de e-commerce moderna con microservicios, patrones DDD y arquitectura hexagonal para escalabilidad empresarial.",
  image: "/templates/ecommerce-microservices.png",
  version: "2.0",
  nodes: [
    {
      id: "web-app",
      type: "square size:200x80",
      position: { x: 50, y: 50 },
      size: { width: 200, height: 80 },
      text: "Web App (React)",
      iconType: "web",
      backgroundColor: "#E3F2FD",
    },
    {
      id: "mobile-app",
      type: "square size:200x80",
      position: { x: 300, y: 50 },
      size: { width: 200, height: 80 },
      text: "Mobile App",
      iconType: "mobile",
      backgroundColor: "#E8F5E8",
    },
    {
      id: "api-gateway-ecom",
      type: "square size:400x100",
      position: { x: 150, y: 180 },
      size: { width: 400, height: 100 },
      text: "API Gateway + Auth Service",
      iconType: "aws-api-gateway",
      backgroundColor: "#FFF3E0",
    },
    {
      id: "user-service",
      type: "square size:180x120",
      position: { x: 80, y: 340 },
      size: { width: 180, height: 120 },
      text: "User Service\n\n• Registration\n• Profile\n• Authentication",
      iconType: "user",
      backgroundColor: "#F3E5F5",
    },
    {
      id: "product-service",
      type: "square size:180x120",
      position: { x: 300, y: 340 },
      size: { width: 180, height: 120 },
      text: "Product Service\n\n• Catalog\n• Inventory\n• Search",
      iconType: "config",
      backgroundColor: "#FCE4EC",
    },
    {
      id: "order-service",
      type: "square size:180x120",
      position: { x: 520, y: 340 },
      size: { width: 180, height: 120 },
      text: "Order Service\n\n• Cart\n• Checkout\n• Order History",
      iconType: "analytics",
      backgroundColor: "#FFF8E1",
    },
    {
      id: "payment-service",
      type: "square size:180x120",
      position: { x: 740, y: 340 },
      size: { width: 180, height: 120 },
      text: "Payment Service\n\n• Stripe/PayPal\n• Billing\n• Refunds",
      iconType: "security",
      backgroundColor: "#E0F2F1",
    },
    {
      id: "notification-ecom",
      type: "square size:180x120",
      position: { x: 960, y: 340 },
      size: { width: 180, height: 120 },
      text: "Notification\nService\n\n• Email\n• SMS\n• Push",
      iconType: "aws-sns",
      backgroundColor: "#EFEBE9",
    },
    {
      id: "user-db",
      type: "square size:140x80",
      position: { x: 100, y: 520 },
      size: { width: 140, height: 80 },
      text: "User DB\n(PostgreSQL)",
      iconType: "database",
      backgroundColor: "#E8EAF6",
    },
    {
      id: "product-db",
      type: "square size:140x80",
      position: { x: 320, y: 520 },
      size: { width: 140, height: 80 },
      text: "Product DB\n(MongoDB)",
      iconType: "database",
      backgroundColor: "#E8EAF6",
    },
    {
      id: "order-db",
      type: "square size:140x80",
      position: { x: 540, y: 520 },
      size: { width: 140, height: 80 },
      text: "Order DB\n(PostgreSQL)",
      iconType: "database",
      backgroundColor: "#E8EAF6",
    },
    {
      id: "event-bus-ecom",
      type: "square size:600x80",
      position: { x: 300, y: 650 },
      size: { width: 600, height: 80 },
      text: "Event Bus (Apache Kafka) - Domain Events",
      iconType: "aws-eventbridge",
      backgroundColor: "#E1F5FE",
    },
    {
      id: "redis-cache",
      type: "square size:200x80",
      position: { x: 50, y: 780 },
      size: { width: 200, height: 80 },
      text: "Redis Cache",
      iconType: "database",
      backgroundColor: "#FFEBEE",
    },
    {
      id: "elasticsearch",
      type: "square size:200x80",
      position: { x: 300, y: 780 },
      size: { width: 200, height: 80 },
      text: "Elasticsearch\n(Product Search)",
      iconType: "analytics",
      backgroundColor: "#FFF3E0",
    },
  ],
  connections: [
    {
      id: "web-to-gateway",
      sourceId: "web-app",
      targetId: "api-gateway-ecom",
      sourcePosition: "bottom",
      targetPosition: "top",
      sourceX: 150,
      sourceY: 130,
      targetX: 300,
      targetY: 180,
      style: "solid",
      animation: "traveling-dot",
      color: "#1976D2",
      strokeWidth: 3,
      endArrowHead: "arrow",
    },
    {
      id: "mobile-to-gateway",
      sourceId: "mobile-app",
      targetId: "api-gateway-ecom",
      sourcePosition: "bottom",
      targetPosition: "top",
      sourceX: 400,
      sourceY: 130,
      targetX: 400,
      targetY: 180,
      style: "solid",
      animation: "traveling-dot",
      color: "#388E3C",
      strokeWidth: 3,
      endArrowHead: "arrow",
    },
    {
      id: "gateway-to-user",
      sourceId: "api-gateway-ecom",
      targetId: "user-service",
      sourcePosition: "bottom",
      targetPosition: "top",
      sourceX: 250,
      sourceY: 280,
      targetX: 170,
      targetY: 340,
      style: "solid",
      animation: "pulse",
      color: "#7B1FA2",
      strokeWidth: 3,
      endArrowHead: "arrow",
    },
    {
      id: "gateway-to-product",
      sourceId: "api-gateway-ecom",
      targetId: "product-service",
      sourcePosition: "bottom",
      targetPosition: "top",
      sourceX: 350,
      sourceY: 280,
      targetX: 390,
      targetY: 340,
      style: "solid",
      animation: "pulse",
      color: "#D32F2F",
      strokeWidth: 3,
      endArrowHead: "arrow",
    },
    {
      id: "gateway-to-order",
      sourceId: "api-gateway-ecom",
      targetId: "order-service",
      sourcePosition: "bottom",
      targetPosition: "top",
      sourceX: 450,
      sourceY: 280,
      targetX: 610,
      targetY: 340,
      style: "solid",
      animation: "pulse",
      color: "#F57C00",
      strokeWidth: 3,
      endArrowHead: "arrow",
    },
    {
      id: "order-to-payment",
      sourceId: "order-service",
      targetId: "payment-service",
      sourcePosition: "right",
      targetPosition: "left",
      sourceX: 700,
      sourceY: 400,
      targetX: 740,
      targetY: 400,
      style: "solid",
      animation: "traveling-dot-fast",
      color: "#689F38",
      strokeWidth: 4,
      endArrowHead: "arrow",
    },
    {
      id: "user-to-db",
      sourceId: "user-service",
      targetId: "user-db",
      sourcePosition: "bottom",
      targetPosition: "top",
      sourceX: 170,
      sourceY: 460,
      targetX: 170,
      targetY: 520,
      style: "solid",
      animation: "traveling-dot",
      color: "#5D4037",
      strokeWidth: 2,
      endArrowHead: "arrow",
    },
    {
      id: "product-to-db",
      sourceId: "product-service",
      targetId: "product-db",
      sourcePosition: "bottom",
      targetPosition: "top",
      sourceX: 390,
      sourceY: 460,
      targetX: 390,
      targetY: 520,
      style: "solid",
      animation: "traveling-dot",
      color: "#5D4037",
      strokeWidth: 2,
      endArrowHead: "arrow",
    },
    {
      id: "order-to-db",
      sourceId: "order-service",
      targetId: "order-db",
      sourcePosition: "bottom",
      targetPosition: "top",
      sourceX: 610,
      sourceY: 460,
      targetX: 610,
      targetY: 520,
      style: "solid",
      animation: "traveling-dot",
      color: "#5D4037",
      strokeWidth: 2,
      endArrowHead: "arrow",
    },
    {
      id: "services-to-eventbus",
      sourceId: "order-service",
      targetId: "event-bus-ecom",
      sourcePosition: "bottom",
      targetPosition: "top",
      sourceX: 610,
      sourceY: 460,
      targetX: 600,
      targetY: 650,
      style: "dashed",
      animation: "dash",
      color: "#FF5722",
      strokeWidth: 3,
      endArrowHead: "arrow",
    },
    {
      id: "eventbus-to-notification",
      sourceId: "event-bus-ecom",
      targetId: "notification-ecom",
      sourcePosition: "top",
      targetPosition: "bottom",
      sourceX: 700,
      sourceY: 650,
      targetX: 1050,
      targetY: 460,
      style: "dashed",
      animation: "dash",
      color: "#607D8B",
      strokeWidth: 2,
      endArrowHead: "arrow",
    },
    {
      id: "product-to-cache",
      sourceId: "product-service",
      targetId: "redis-cache",
      sourcePosition: "bottom",
      targetPosition: "top",
      sourceX: 300,
      sourceY: 460,
      targetX: 150,
      targetY: 780,
      style: "dotted",
      animation: "flow",
      color: "#795548",
      strokeWidth: 2,
      endArrowHead: "arrow",
    },
    {
      id: "product-to-search",
      sourceId: "product-service",
      targetId: "elasticsearch",
      sourcePosition: "bottom",
      targetPosition: "top",
      sourceX: 390,
      sourceY: 460,
      targetX: 400,
      targetY: 780,
      style: "dotted",
      animation: "flow",
      color: "#FF9800",
      strokeWidth: 2,
      endArrowHead: "arrow",
    },
  ],
  viewport: {
    scale: 0.5,
    position: { x: 120, y: 100 },
  },
  metadata: {
    exportedAt: new Date().toISOString(),
    nodeCount: 14,
    connectionCount: 13,
  },
};

// 🌐 PLANTILLA 5: Edge Computing & CDN
const edgeComputingTemplate: TemplateType = {
  id: "edge-computing-cdn",
  name: "🌐 Edge Computing & Global CDN",
  description:
    "Arquitectura global de edge computing con CDN distribuido para latencia ultra-baja y experiencia optimizada worldwide.",
  image: "/templates/edge-computing.png",
  version: "2.0",
  nodes: [
    {
      id: "users-global",
      type: "square size:250x100",
      position: { x: 50, y: 50 },
      size: { width: 250, height: 100 },
      text: "Global Users\n(Mobile & Web)",
      iconType: "user",
      backgroundColor: "#E3F2FD",
    },
    {
      id: "cloudflare-cdn",
      type: "square size:400x120",
      position: { x: 400, y: 30 },
      size: { width: 400, height: 120 },
      text: "Global CDN (Cloudflare)\n\n• 200+ Edge Locations\n• Smart Routing\n• DDoS Protection",
      iconType: "aws-cloudfront",
      backgroundColor: "#FFF3E0",
    },
    {
      id: "edge-us-east",
      type: "square size:200x120",
      position: { x: 100, y: 220 },
      size: { width: 200, height: 120 },
      text: "Edge US-East\n\n• Compute@Edge\n• Static Cache\n• API Cache",
      iconType: "server",
      backgroundColor: "#E8F5E8",
    },
    {
      id: "edge-europe",
      type: "square size:200x120",
      position: { x: 350, y: 220 },
      size: { width: 200, height: 120 },
      text: "Edge Europe\n\n• Compute@Edge\n• Static Cache\n• API Cache",
      iconType: "server",
      backgroundColor: "#F3E5F5",
    },
    {
      id: "edge-asia",
      type: "square size:200x120",
      position: { x: 600, y: 220 },
      size: { width: 200, height: 120 },
      text: "Edge Asia-Pacific\n\n• Compute@Edge\n• Static Cache\n• API Cache",
      iconType: "server",
      backgroundColor: "#FCE4EC",
    },
    {
      id: "origin-servers",
      type: "square size:350x100",
      position: { x: 300, y: 400 },
      size: { width: 350, height: 100 },
      text: "Origin Servers (AWS/GCP)\n\nPrimary Application Stack",
      iconType: "cloud",
      backgroundColor: "#FFF8E1",
    },
    {
      id: "edge-storage",
      type: "square size:220x80",
      position: { x: 80, y: 570 },
      size: { width: 220, height: 80 },
      text: "Edge Storage\n(Redis Global)",
      iconType: "database",
      backgroundColor: "#E0F2F1",
    },
    {
      id: "edge-analytics",
      type: "square size:220x80",
      position: { x: 350, y: 570 },
      size: { width: 220, height: 80 },
      text: "Real-time Analytics\n(Edge Computing)",
      iconType: "analytics",
      backgroundColor: "#EFEBE9",
    },
    {
      id: "edge-security",
      type: "square size:220x80",
      position: { x: 620, y: 570 },
      size: { width: 220, height: 80 },
      text: "Edge Security\n(WAF + Bot Protection)",
      iconType: "security",
      backgroundColor: "#E1F5FE",
    },
  ],
  connections: [
    {
      id: "users-to-cdn",
      sourceId: "users-global",
      targetId: "cloudflare-cdn",
      sourcePosition: "right",
      targetPosition: "left",
      sourceX: 300,
      sourceY: 100,
      targetX: 400,
      targetY: 90,
      style: "solid",
      animation: "traveling-dot-fastest",
      color: "#FF6F00",
      strokeWidth: 4,
      endArrowHead: "arrow",
    },
    {
      id: "cdn-to-edge-us",
      sourceId: "cloudflare-cdn",
      targetId: "edge-us-east",
      sourcePosition: "bottom",
      targetPosition: "top",
      sourceX: 500,
      sourceY: 150,
      targetX: 200,
      targetY: 220,
      style: "solid",
      animation: "traveling-dot-fast",
      color: "#1976D2",
      strokeWidth: 3,
      endArrowHead: "arrow",
    },
    {
      id: "cdn-to-edge-eu",
      sourceId: "cloudflare-cdn",
      targetId: "edge-europe",
      sourcePosition: "bottom",
      targetPosition: "top",
      sourceX: 600,
      sourceY: 150,
      targetX: 450,
      targetY: 220,
      style: "solid",
      animation: "traveling-dot-fast",
      color: "#7B1FA2",
      strokeWidth: 3,
      endArrowHead: "arrow",
    },
    {
      id: "cdn-to-edge-asia",
      sourceId: "cloudflare-cdn",
      targetId: "edge-asia",
      sourcePosition: "bottom",
      targetPosition: "top",
      sourceX: 700,
      sourceY: 150,
      targetX: 700,
      targetY: 220,
      style: "solid",
      animation: "traveling-dot-fast",
      color: "#388E3C",
      strokeWidth: 3,
      endArrowHead: "arrow",
    },
    {
      id: "edge-us-to-origin",
      sourceId: "edge-us-east",
      targetId: "origin-servers",
      sourcePosition: "bottom",
      targetPosition: "top",
      sourceX: 200,
      sourceY: 340,
      targetX: 400,
      targetY: 400,
      style: "dashed",
      animation: "dash",
      color: "#D32F2F",
      strokeWidth: 2,
      endArrowHead: "arrow",
    },
    {
      id: "edge-eu-to-origin",
      sourceId: "edge-europe",
      targetId: "origin-servers",
      sourcePosition: "bottom",
      targetPosition: "top",
      sourceX: 450,
      sourceY: 340,
      targetX: 475,
      targetY: 400,
      style: "dashed",
      animation: "dash",
      color: "#D32F2F",
      strokeWidth: 2,
      endArrowHead: "arrow",
    },
    {
      id: "edge-asia-to-origin",
      sourceId: "edge-asia",
      targetId: "origin-servers",
      sourcePosition: "bottom",
      targetPosition: "top",
      sourceX: 700,
      sourceY: 340,
      targetX: 550,
      targetY: 400,
      style: "dashed",
      animation: "dash",
      color: "#D32F2F",
      strokeWidth: 2,
      endArrowHead: "arrow",
    },
    {
      id: "edge-to-storage",
      sourceId: "edge-us-east",
      targetId: "edge-storage",
      sourcePosition: "bottom",
      targetPosition: "top",
      sourceX: 150,
      sourceY: 340,
      targetX: 190,
      targetY: 570,
      style: "dotted",
      animation: "flow",
      color: "#607D8B",
      strokeWidth: 2,
      endArrowHead: "arrow",
    },
    {
      id: "edge-to-analytics",
      sourceId: "edge-europe",
      targetId: "edge-analytics",
      sourcePosition: "bottom",
      targetPosition: "top",
      sourceX: 450,
      sourceY: 340,
      targetX: 460,
      targetY: 570,
      style: "dotted",
      animation: "flow",
      color: "#FF9800",
      strokeWidth: 2,
      endArrowHead: "arrow",
    },
    {
      id: "edge-to-security",
      sourceId: "edge-asia",
      targetId: "edge-security",
      sourcePosition: "bottom",
      targetPosition: "top",
      sourceX: 700,
      sourceY: 340,
      targetX: 730,
      targetY: 570,
      style: "dotted",
      animation: "flow",
      color: "#795548",
      strokeWidth: 2,
      endArrowHead: "arrow",
    },
  ],
  viewport: {
    scale: 0.8,
    position: { x: 80, y: 60 },
  },
  metadata: {
    exportedAt: new Date().toISOString(),
    nodeCount: 9,
    connectionCount: 10,
  },
};

// 🚢 PLANTILLA 6: Kubernetes Cloud Native
const kubernetesCloudNativeTemplate: TemplateType = {
  id: "kubernetes-cloud-native",
  name: "🚢 Kubernetes Cloud Native",
  description:
    "Arquitectura nativa de la nube con Kubernetes, service mesh, observabilidad y GitOps para máxima escalabilidad.",
  image: "/templates/kubernetes-cloud-native.png",
  version: "2.0",
  nodes: [
    {
      id: "developer",
      type: "square size:200x80",
      position: { x: 50, y: 50 },
      size: { width: 200, height: 80 },
      text: "Developer\n(Local Development)",
      iconType: "user",
      backgroundColor: "#E3F2FD",
    },
    {
      id: "git-repo",
      type: "square size:200x80",
      position: { x: 350, y: 50 },
      size: { width: 200, height: 80 },
      text: "Git Repository\n(GitHub/GitLab)",
      iconType: "config",
      backgroundColor: "#F3E5F5",
    },
    {
      id: "ci-cd",
      type: "square size:300x100",
      position: { x: 650, y: 30 },
      size: { width: 300, height: 100 },
      text: "CI/CD Pipeline\n\n• GitHub Actions\n• ArgoCD (GitOps)",
      iconType: "aws-lambda",
      backgroundColor: "#FFF3E0",
    },
    {
      id: "container-registry",
      type: "square size:220x80",
      position: { x: 1050, y: 50 },
      size: { width: 220, height: 80 },
      text: "Container Registry\n(Harbor/ECR)",
      iconType: "database",
      backgroundColor: "#E8F5E8",
    },
    {
      id: "k8s-cluster",
      type: "square size:800x300",
      position: { x: 200, y: 200 },
      size: { width: 800, height: 300 },
      text: "Kubernetes Cluster (EKS/GKE/AKS)\n\n🔹 Ingress Controller (NGINX/Istio)\n🔹 Service Mesh (Istio/Linkerd)\n🔹 Pod Autoscaling (HPA/VPA)\n🔹 Network Policies\n🔹 Resource Quotas\n🔹 Security Policies (OPA Gatekeeper)",
      iconType: "cloud",
      backgroundColor: "#E1F5FE",
    },
    {
      id: "microservice-a",
      type: "square size:150x100",
      position: { x: 250, y: 280 },
      size: { width: 150, height: 100 },
      text: "User Service\n\n• 3 Replicas\n• Health Checks",
      iconType: "api",
      backgroundColor: "#FCE4EC",
    },
    {
      id: "microservice-b",
      type: "square size:150x100",
      position: { x: 450, y: 280 },
      size: { width: 150, height: 100 },
      text: "Order Service\n\n• 5 Replicas\n• Circuit Breaker",
      iconType: "api",
      backgroundColor: "#FFF8E1",
    },
    {
      id: "microservice-c",
      type: "square size:150x100",
      position: { x: 650, y: 280 },
      size: { width: 150, height: 100 },
      text: "Payment Service\n\n• 2 Replicas\n• Rate Limiting",
      iconType: "api",
      backgroundColor: "#E0F2F1",
    },
    {
      id: "databases",
      type: "square size:200x100",
      position: { x: 850, y: 280 },
      size: { width: 200, height: 100 },
      text: "Databases\n\n• PostgreSQL\n• Redis\n• MongoDB",
      iconType: "database",
      backgroundColor: "#EFEBE9",
    },
    {
      id: "observability",
      type: "square size:350x120",
      position: { x: 100, y: 580 },
      size: { width: 350, height: 120 },
      text: "Observability Stack\n\n• Prometheus (Metrics)\n• Grafana (Dashboards)\n• Jaeger (Tracing)\n• ELK (Logging)",
      iconType: "analytics",
      backgroundColor: "#E8EAF6",
    },
    {
      id: "security-scanning",
      type: "square size:300x120",
      position: { x: 500, y: 580 },
      size: { width: 300, height: 120 },
      text: "Security & Compliance\n\n• Falco (Runtime Security)\n• Trivy (Vulnerability Scan)\n• OPA (Policy Engine)",
      iconType: "security",
      backgroundColor: "#FFEBEE",
    },
    {
      id: "backup-dr",
      type: "square size:250x120",
      position: { x: 850, y: 580 },
      size: { width: 250, height: 120 },
      text: "Backup & DR\n\n• Velero\n• Cross-region replication\n• Disaster Recovery",
      iconType: "database",
      backgroundColor: "#E4F3E7",
    },
  ],
  connections: [
    {
      id: "dev-to-git",
      sourceId: "developer",
      targetId: "git-repo",
      sourcePosition: "right",
      targetPosition: "left",
      sourceX: 250,
      sourceY: 90,
      targetX: 350,
      targetY: 90,
      style: "solid",
      animation: "traveling-dot",
      color: "#1976D2",
      strokeWidth: 3,
      endArrowHead: "arrow",
    },
    {
      id: "git-to-cicd",
      sourceId: "git-repo",
      targetId: "ci-cd",
      sourcePosition: "right",
      targetPosition: "left",
      sourceX: 550,
      sourceY: 90,
      targetX: 650,
      targetY: 80,
      style: "solid",
      animation: "traveling-dot-fast",
      color: "#388E3C",
      strokeWidth: 3,
      endArrowHead: "arrow",
    },
    {
      id: "cicd-to-registry",
      sourceId: "ci-cd",
      targetId: "container-registry",
      sourcePosition: "right",
      targetPosition: "left",
      sourceX: 950,
      sourceY: 80,
      targetX: 1050,
      targetY: 90,
      style: "solid",
      animation: "pulse",
      color: "#7B1FA2",
      strokeWidth: 4,
      endArrowHead: "arrow",
    },
    {
      id: "cicd-to-k8s",
      sourceId: "ci-cd",
      targetId: "k8s-cluster",
      sourcePosition: "bottom",
      targetPosition: "top",
      sourceX: 800,
      sourceY: 130,
      targetX: 600,
      targetY: 200,
      style: "solid",
      animation: "traveling-dot-fastest",
      color: "#D32F2F",
      strokeWidth: 4,
      endArrowHead: "arrow",
    },
    {
      id: "registry-to-k8s",
      sourceId: "container-registry",
      targetId: "k8s-cluster",
      sourcePosition: "bottom",
      targetPosition: "top",
      sourceX: 1160,
      sourceY: 130,
      targetX: 800,
      targetY: 200,
      style: "dashed",
      animation: "dash",
      color: "#F57C00",
      strokeWidth: 2,
      endArrowHead: "arrow",
    },
    {
      id: "service-communication",
      sourceId: "microservice-a",
      targetId: "microservice-b",
      sourcePosition: "right",
      targetPosition: "left",
      sourceX: 400,
      sourceY: 330,
      targetX: 450,
      targetY: 330,
      style: "solid",
      animation: "traveling-dot",
      color: "#9C27B0",
      strokeWidth: 2,
      endArrowHead: "arrow",
    },
    {
      id: "service-to-payment",
      sourceId: "microservice-b",
      targetId: "microservice-c",
      sourcePosition: "right",
      targetPosition: "left",
      sourceX: 600,
      sourceY: 330,
      targetX: 650,
      targetY: 330,
      style: "solid",
      animation: "traveling-dot",
      color: "#9C27B0",
      strokeWidth: 2,
      endArrowHead: "arrow",
    },
    {
      id: "services-to-db",
      sourceId: "microservice-c",
      targetId: "databases",
      sourcePosition: "right",
      targetPosition: "left",
      sourceX: 800,
      sourceY: 330,
      targetX: 850,
      targetY: 330,
      style: "solid",
      animation: "traveling-dot-fast",
      color: "#689F38",
      strokeWidth: 3,
      endArrowHead: "arrow",
    },
    {
      id: "k8s-to-observability",
      sourceId: "k8s-cluster",
      targetId: "observability",
      sourcePosition: "bottom",
      targetPosition: "top",
      sourceX: 400,
      sourceY: 500,
      targetX: 275,
      targetY: 580,
      style: "dotted",
      animation: "flow",
      color: "#607D8B",
      strokeWidth: 2,
      endArrowHead: "arrow",
    },
    {
      id: "k8s-to-security",
      sourceId: "k8s-cluster",
      targetId: "security-scanning",
      sourcePosition: "bottom",
      targetPosition: "top",
      sourceX: 600,
      sourceY: 500,
      targetX: 650,
      targetY: 580,
      style: "dotted",
      animation: "flow",
      color: "#FF5722",
      strokeWidth: 2,
      endArrowHead: "arrow",
    },
    {
      id: "k8s-to-backup",
      sourceId: "k8s-cluster",
      targetId: "backup-dr",
      sourcePosition: "bottom",
      targetPosition: "top",
      sourceX: 800,
      sourceY: 500,
      targetX: 975,
      targetY: 580,
      style: "dotted",
      animation: "flow",
      color: "#795548",
      strokeWidth: 2,
      endArrowHead: "arrow",
    },
  ],
  viewport: {
    scale: 0.5,
    position: { x: 100, y: 80 },
  },
  metadata: {
    exportedAt: new Date().toISOString(),
    nodeCount: 12,
    connectionCount: 11,
  },
};

// 🤖 PLANTILLA 7: ML & Data Pipeline
const mlDataPipelineTemplate: TemplateType = {
  id: "ml-data-pipeline",
  name: "🤖 ML & Data Pipeline",
  description:
    "Pipeline completo de Machine Learning con ingesta de datos, entrenamiento, deployment y monitoreo en producción.",
  image: "/templates/ml-data-pipeline.png",
  version: "2.0",
  nodes: [
    {
      id: "data-sources",
      type: "square size:300x120",
      position: { x: 50, y: 50 },
      size: { width: 300, height: 120 },
      text: "Data Sources\n\n• APIs (REST/GraphQL)\n• Databases (OLTP)\n• Files (CSV/JSON/Parquet)\n• Streaming (Kafka)",
      iconType: "database",
      backgroundColor: "#E3F2FD",
    },
    {
      id: "data-ingestion",
      type: "square size:280x100",
      position: { x: 450, y: 70 },
      size: { width: 280, height: 100 },
      text: "Data Ingestion\n\n• Apache Airflow\n• AWS Glue\n• Apache Spark",
      iconType: "aws-lambda",
      backgroundColor: "#FFF3E0",
    },
    {
      id: "raw-data-lake",
      type: "square size:250x100",
      position: { x: 800, y: 70 },
      size: { width: 250, height: 100 },
      text: "Raw Data Lake\n\n• S3/ADLS/GCS\n• Delta Lake\n• Versioning",
      iconType: "aws-s3",
      backgroundColor: "#E8F5E8",
    },
    {
      id: "data-processing",
      type: "square size:350x120",
      position: { x: 200, y: 250 },
      size: { width: 350, height: 120 },
      text: "Data Processing & ETL\n\n• Apache Spark/Databricks\n• Data Quality Checks\n• Feature Engineering\n• Data Validation",
      iconType: "analytics",
      backgroundColor: "#F3E5F5",
    },
    {
      id: "feature-store",
      type: "square size:250x100",
      position: { x: 650, y: 270 },
      size: { width: 250, height: 100 },
      text: "Feature Store\n\n• Feast/Tecton\n• Feature Catalog\n• Feature Serving",
      iconType: "database",
      backgroundColor: "#FCE4EC",
    },
    {
      id: "ml-training",
      type: "square size:300x120",
      position: { x: 100, y: 450 },
      size: { width: 300, height: 120 },
      text: "ML Training\n\n• MLflow/Kubeflow\n• AutoML (H2O.ai)\n• Hyperparameter Tuning\n• Cross Validation",
      iconType: "cloud",
      backgroundColor: "#FFF8E1",
    },
    {
      id: "model-registry",
      type: "square size:250x100",
      position: { x: 500, y: 470 },
      size: { width: 250, height: 100 },
      text: "Model Registry\n\n• MLflow Registry\n• Model Versioning\n• A/B Testing",
      iconType: "config",
      backgroundColor: "#E0F2F1",
    },
    {
      id: "model-serving",
      type: "square size:280x120",
      position: { x: 820, y: 450 },
      size: { width: 280, height: 120 },
      text: "Model Serving\n\n• Kubernetes/KServe\n• REST/gRPC APIs\n• Batch Inference\n• Real-time Prediction",
      iconType: "api",
      backgroundColor: "#EFEBE9",
    },
    {
      id: "ml-monitoring",
      type: "square size:350x100",
      position: { x: 300, y: 650 },
      size: { width: 350, height: 100 },
      text: "ML Monitoring & Observability\n\n• Model Drift Detection • Data Quality\n• Performance Metrics • Alerts",
      iconType: "analytics",
      backgroundColor: "#E1F5FE",
    },
    {
      id: "applications",
      type: "square size:250x100",
      position: { x: 750, y: 650 },
      size: { width: 250, height: 100 },
      text: "Applications\n\n• Web Apps\n• Mobile Apps\n• Business Intelligence",
      iconType: "web",
      backgroundColor: "#E8EAF6",
    },
  ],
  connections: [
    {
      id: "sources-to-ingestion",
      sourceId: "data-sources",
      targetId: "data-ingestion",
      sourcePosition: "right",
      targetPosition: "left",
      sourceX: 350,
      sourceY: 110,
      targetX: 450,
      targetY: 120,
      style: "solid",
      animation: "traveling-dot-fast",
      color: "#1976D2",
      strokeWidth: 4,
      endArrowHead: "arrow",
    },
    {
      id: "ingestion-to-lake",
      sourceId: "data-ingestion",
      targetId: "raw-data-lake",
      sourcePosition: "right",
      targetPosition: "left",
      sourceX: 730,
      sourceY: 120,
      targetX: 800,
      targetY: 120,
      style: "solid",
      animation: "traveling-dot",
      color: "#388E3C",
      strokeWidth: 3,
      endArrowHead: "arrow",
    },
    {
      id: "lake-to-processing",
      sourceId: "raw-data-lake",
      targetId: "data-processing",
      sourcePosition: "bottom",
      targetPosition: "top",
      sourceX: 925,
      sourceY: 170,
      targetX: 375,
      targetY: 250,
      style: "solid",
      animation: "pulse",
      color: "#7B1FA2",
      strokeWidth: 4,
      endArrowHead: "arrow",
    },
    {
      id: "processing-to-features",
      sourceId: "data-processing",
      targetId: "feature-store",
      sourcePosition: "right",
      targetPosition: "left",
      sourceX: 550,
      sourceY: 310,
      targetX: 650,
      targetY: 320,
      style: "solid",
      animation: "traveling-dot-fast",
      color: "#D32F2F",
      strokeWidth: 3,
      endArrowHead: "arrow",
    },
    {
      id: "features-to-training",
      sourceId: "feature-store",
      targetId: "ml-training",
      sourcePosition: "bottom",
      targetPosition: "top",
      sourceX: 775,
      sourceY: 370,
      targetX: 250,
      targetY: 450,
      style: "solid",
      animation: "traveling-dot",
      color: "#F57C00",
      strokeWidth: 3,
      endArrowHead: "arrow",
    },
    {
      id: "training-to-registry",
      sourceId: "ml-training",
      targetId: "model-registry",
      sourcePosition: "right",
      targetPosition: "left",
      sourceX: 400,
      sourceY: 510,
      targetX: 500,
      targetY: 520,
      style: "solid",
      animation: "pulse",
      color: "#689F38",
      strokeWidth: 4,
      endArrowHead: "arrow",
    },
    {
      id: "registry-to-serving",
      sourceId: "model-registry",
      targetId: "model-serving",
      sourcePosition: "right",
      targetPosition: "left",
      sourceX: 750,
      sourceY: 520,
      targetX: 820,
      targetY: 510,
      style: "solid",
      animation: "traveling-dot-fastest",
      color: "#9C27B0",
      strokeWidth: 4,
      endArrowHead: "arrow",
    },
    {
      id: "serving-to-apps",
      sourceId: "model-serving",
      targetId: "applications",
      sourcePosition: "bottom",
      targetPosition: "top",
      sourceX: 960,
      sourceY: 570,
      targetX: 875,
      targetY: 650,
      style: "solid",
      animation: "traveling-dot",
      color: "#FF5722",
      strokeWidth: 3,
      endArrowHead: "arrow",
    },
    {
      id: "serving-to-monitoring",
      sourceId: "model-serving",
      targetId: "ml-monitoring",
      sourcePosition: "bottom",
      targetPosition: "top",
      sourceX: 860,
      sourceY: 570,
      targetX: 475,
      targetY: 650,
      style: "dashed",
      animation: "dash",
      color: "#607D8B",
      strokeWidth: 2,
      endArrowHead: "arrow",
    },
    {
      id: "monitoring-feedback",
      sourceId: "ml-monitoring",
      targetId: "data-processing",
      sourcePosition: "top",
      targetPosition: "bottom",
      sourceX: 375,
      sourceY: 650,
      targetX: 375,
      targetY: 370,
      style: "dotted",
      animation: "flow",
      color: "#795548",
      strokeWidth: 2,
      endArrowHead: "arrow",
    },
  ],
  viewport: {
    scale: 0.6,
    position: { x: 80, y: 60 },
  },
  metadata: {
    exportedAt: new Date().toISOString(),
    nodeCount: 10,
    connectionCount: 10,
  },
};

// 📡 PLANTILLA 8: IoT & Real-time Analytics
const iotRealTimeTemplate: TemplateType = {
  id: "iot-realtime-analytics",
  name: "📡 IoT & Real-time Analytics",
  description:
    "Plataforma IoT empresarial con analytics en tiempo real, edge computing y machine learning para smart cities y industria 4.0.",
  image: "/templates/iot-realtime.png",
  version: "2.0",
  nodes: [
    {
      id: "iot-devices",
      type: "square size:280x120",
      position: { x: 50, y: 50 },
      size: { width: 280, height: 120 },
      text: "IoT Devices\n\n• Sensors (Temperature, Pressure)\n• Smart Cameras\n• Industrial Equipment\n• Wearables & Trackers",
      iconType: "mobile",
      backgroundColor: "#E3F2FD",
    },
    {
      id: "edge-gateway",
      type: "square size:250x100",
      position: { x: 450, y: 70 },
      size: { width: 250, height: 100 },
      text: "Edge Gateway\n\n• Data Preprocessing\n• Local Analytics\n• Offline Storage",
      iconType: "server",
      backgroundColor: "#FFF3E0",
    },
    {
      id: "device-management",
      type: "square size:220x80",
      position: { x: 780, y: 80 },
      size: { width: 220, height: 80 },
      text: "Device Management\n(AWS IoT Core)",
      iconType: "config",
      backgroundColor: "#E8F5E8",
    },
    {
      id: "message-broker",
      type: "square size:350x100",
      position: { x: 200, y: 250 },
      size: { width: 350, height: 100 },
      text: "Message Broker\n\n• MQTT (Mosquitto/HiveMQ)\n• Apache Kafka\n• Azure IoT Hub",
      iconType: "aws-eventbridge",
      backgroundColor: "#F3E5F5",
    },
    {
      id: "stream-processing",
      type: "square size:300x120",
      position: { x: 650, y: 230 },
      size: { width: 300, height: 120 },
      text: "Stream Processing\n\n• Apache Kafka Streams\n• Azure Stream Analytics\n• Real-time Aggregation\n• Complex Event Processing",
      iconType: "analytics",
      backgroundColor: "#FCE4EC",
    },
    {
      id: "time-series-db",
      type: "square size:250x100",
      position: { x: 100, y: 420 },
      size: { width: 250, height: 100 },
      text: "Time-Series DB\n\n• InfluxDB\n• TimescaleDB\n• AWS Timestream",
      iconType: "database",
      backgroundColor: "#FFF8E1",
    },
    {
      id: "data-lake-iot",
      type: "square size:250x100",
      position: { x: 450, y: 420 },
      size: { width: 250, height: 100 },
      text: "Data Lake\n\n• Raw Sensor Data\n• Historical Analytics\n• Data Archiving",
      iconType: "aws-s3",
      backgroundColor: "#E0F2F1",
    },
    {
      id: "ml-inference",
      type: "square size:250x100",
      position: { x: 800, y: 420 },
      size: { width: 250, height: 100 },
      text: "ML Inference\n\n• Anomaly Detection\n• Predictive Maintenance\n• Pattern Recognition",
      iconType: "cloud",
      backgroundColor: "#EFEBE9",
    },
    {
      id: "real-time-dashboard",
      type: "square size:300x100",
      position: { x: 150, y: 580 },
      size: { width: 300, height: 100 },
      text: "Real-time Dashboards\n\n• Grafana • Kibana\n• Custom Web Apps",
      iconType: "web",
      backgroundColor: "#E1F5FE",
    },
    {
      id: "alerting-system",
      type: "square size:250x100",
      position: { x: 550, y: 580 },
      size: { width: 250, height: 100 },
      text: "Alerting System\n\n• Threshold Monitoring\n• SMS/Email Alerts\n• Webhook Integration",
      iconType: "aws-sns",
      backgroundColor: "#E8EAF6",
    },
    {
      id: "control-system",
      type: "square size:250x100",
      position: { x: 850, y: 580 },
      size: { width: 250, height: 100 },
      text: "Control System\n\n• Remote Commands\n• Automated Actions\n• SCADA Integration",
      iconType: "security",
      backgroundColor: "#FFEBEE",
    },
  ],
  connections: [
    {
      id: "devices-to-gateway",
      sourceId: "iot-devices",
      targetId: "edge-gateway",
      sourcePosition: "right",
      targetPosition: "left",
      sourceX: 330,
      sourceY: 110,
      targetX: 450,
      targetY: 120,
      style: "solid",
      animation: "traveling-dot-fastest",
      color: "#FF6F00",
      strokeWidth: 4,
      endArrowHead: "arrow",
    },
    {
      id: "devices-to-management",
      sourceId: "iot-devices",
      targetId: "device-management",
      sourcePosition: "top",
      targetPosition: "bottom",
      sourceX: 280,
      sourceY: 50,
      targetX: 890,
      targetY: 160,
      style: "dashed",
      animation: "dash",
      color: "#607D8B",
      strokeWidth: 2,
      endArrowHead: "arrow",
    },
    {
      id: "gateway-to-broker",
      sourceId: "edge-gateway",
      targetId: "message-broker",
      sourcePosition: "bottom",
      targetPosition: "top",
      sourceX: 575,
      sourceY: 170,
      targetX: 375,
      targetY: 250,
      style: "solid",
      animation: "traveling-dot-fast",
      color: "#1976D2",
      strokeWidth: 4,
      endArrowHead: "arrow",
    },
    {
      id: "broker-to-stream",
      sourceId: "message-broker",
      targetId: "stream-processing",
      sourcePosition: "right",
      targetPosition: "left",
      sourceX: 550,
      sourceY: 300,
      targetX: 650,
      targetY: 290,
      style: "solid",
      animation: "pulse",
      color: "#7B1FA2",
      strokeWidth: 4,
      endArrowHead: "arrow",
    },
    {
      id: "stream-to-timeseries",
      sourceId: "stream-processing",
      targetId: "time-series-db",
      sourcePosition: "bottom",
      targetPosition: "top",
      sourceX: 700,
      sourceY: 350,
      targetX: 225,
      targetY: 420,
      style: "solid",
      animation: "traveling-dot",
      color: "#388E3C",
      strokeWidth: 3,
      endArrowHead: "arrow",
    },
    {
      id: "stream-to-datalake",
      sourceId: "stream-processing",
      targetId: "data-lake-iot",
      sourcePosition: "bottom",
      targetPosition: "top",
      sourceX: 800,
      sourceY: 350,
      targetX: 575,
      targetY: 420,
      style: "solid",
      animation: "traveling-dot",
      color: "#D32F2F",
      strokeWidth: 3,
      endArrowHead: "arrow",
    },
    {
      id: "stream-to-ml",
      sourceId: "stream-processing",
      targetId: "ml-inference",
      sourcePosition: "bottom",
      targetPosition: "top",
      sourceX: 850,
      sourceY: 350,
      targetX: 925,
      targetY: 420,
      style: "solid",
      animation: "traveling-dot-fast",
      color: "#F57C00",
      strokeWidth: 3,
      endArrowHead: "arrow",
    },
    {
      id: "timeseries-to-dashboard",
      sourceId: "time-series-db",
      targetId: "real-time-dashboard",
      sourcePosition: "bottom",
      targetPosition: "top",
      sourceX: 225,
      sourceY: 520,
      targetX: 300,
      targetY: 580,
      style: "solid",
      animation: "flow",
      color: "#689F38",
      strokeWidth: 3,
      endArrowHead: "arrow",
    },
    {
      id: "ml-to-alerts",
      sourceId: "ml-inference",
      targetId: "alerting-system",
      sourcePosition: "bottom",
      targetPosition: "top",
      sourceX: 925,
      sourceY: 520,
      targetX: 675,
      targetY: 580,
      style: "dashed",
      animation: "dash",
      color: "#9C27B0",
      strokeWidth: 3,
      endArrowHead: "arrow",
    },
    {
      id: "ml-to-control",
      sourceId: "ml-inference",
      targetId: "control-system",
      sourcePosition: "bottom",
      targetPosition: "top",
      sourceX: 975,
      sourceY: 520,
      targetX: 975,
      targetY: 580,
      style: "solid",
      animation: "traveling-dot",
      color: "#FF5722",
      strokeWidth: 3,
      endArrowHead: "arrow",
    },
    {
      id: "control-to-devices",
      sourceId: "control-system",
      targetId: "iot-devices",
      sourcePosition: "top",
      targetPosition: "bottom",
      sourceX: 975,
      sourceY: 580,
      targetX: 190,
      targetY: 170,
      style: "dotted",
      animation: "flow",
      color: "#795548",
      strokeWidth: 2,
      endArrowHead: "arrow",
    },
  ],
  viewport: {
    scale: 0.6,
    position: { x: 80, y: 60 },
  },
  metadata: {
    exportedAt: new Date().toISOString(),
    nodeCount: 11,
    connectionCount: 11,
  },
};

// Export the new professional templates
export const useTemplates = () => {
  return {
    templates: [
      eventDrivenTemplate,
      cqrsEventSourcingTemplate,
      multiCloudTemplate,
      ecommerceMicroservicesTemplate,
      edgeComputingTemplate,
      kubernetesCloudNativeTemplate,
      mlDataPipelineTemplate,
      iotRealTimeTemplate,
    ],
  };
};
