export const queueStyles = {
  container:
    "w-full h-full rounded-lg border-2 border-slate-300 bg-white shadow-sm flex flex-col overflow-hidden relative transition-all hover:shadow-md",
  containerPaused: "border-amber-400",
  header: "flex items-center justify-center gap-2 px-4 pt-3 pb-2",
  iconBadge: "flex h-5 w-5 items-center justify-center shrink-0",
  titleWrapper: "flex items-center justify-center",
  titleText: "text-sm font-semibold text-slate-700 truncate",
  trackWrapper: "relative flex-1 px-4 flex items-center min-h-[50px]",
  track: "relative w-full h-full rounded-lg bg-slate-50 border border-slate-200",
  trackBackground: "absolute inset-0 bg-gradient-to-r from-blue-50/50 via-slate-50 to-green-50/50",
  trackOverlay: "pointer-events-none absolute inset-0 flex items-center justify-between px-2",
  trackMarker: "flex items-center justify-center",
  markerBadge: "text-xs font-bold text-slate-400 bg-white/80 px-2 py-0.5 rounded",
  pauseBadge: "absolute left-2 top-2 text-xs bg-amber-100 text-amber-700 px-2 py-0.5 rounded",
  message:
    "absolute rounded-full border-2 border-white shadow-md flex items-center justify-center font-bold text-white text-xs transition-all will-change-transform",
  messageEntering: "",
  messageLeaving: "",
  messageId: "text-[10px] leading-none",
  footer: "flex items-center justify-center px-4 pb-3 pt-2",
  footerInfo: "flex items-center gap-2 text-xs text-slate-500",
  footerLabel: "font-medium",
  footerDot: "text-slate-300",
  statusDot: "h-2 w-2 rounded-full inline-block",
  animationContainer: "relative w-full h-full",
};

export const colorPickerStyles = {
  preview: "mb-6 flex flex-col items-center",
  previewColor: "w-24 h-24 rounded-lg shadow-md border border-gray-200 mb-2",
  colorValue: "text-sm font-mono",
  section: "mb-6",
  label: "block text-sm font-medium text-gray-700 mb-2",
  colorInputContainer: "flex items-center gap-4",
  colorInput: "h-10 w-10 border-0 p-0 cursor-pointer",
  hexInput: "flex-1 border border-gray-300 px-3 py-2 rounded-md text-sm focus:outline-none",
  colorsGrid: "grid grid-cols-5 gap-2",
  colorButton: "w-full aspect-square rounded-md border",
  colorButtonSelected: "border-2 border-blue-500",
  colorButtonHover: "",
  cancelButton: "px-4 py-2 bg-gray-200 text-gray-800 rounded-md",
  applyButton: "px-4 py-2 bg-blue-600 text-white rounded-md",
};
